import {i18n,detectLanguage} from '../data/i18n.js';
import {games} from '../data/games.js';
import {state} from './state.js';
import {initTelegram,tg,getTelegramUser,openExternal,openSupport} from './services/telegram.js';
import {startChat,stopChat,handleSubmit,focusInput} from './domains/chat/chat.js';
import {liveDomain,bettingDomain} from './domains/index.js';
import {renderTopbar} from './components/topbar.js';
import {renderBottomNav} from './components/bottomNav.js';
import {renderModal,openDepositModal,openWithdrawModal,closeModal} from './components/modal.js';
import {renderBettingSheet,openBetting,closeBetting,handleBetClick,updateBetUI} from './components/bettingSheet.js';
import {renderHome} from './pages/home.js';
import {renderLive} from './pages/live.js';
import {renderRoom} from './pages/room.js';
import {renderMini} from './pages/mini.js';
import {renderProfile} from './pages/profile.js';
import {createRouter} from './pages/router.js';

initTelegram();
document.documentElement.dataset.platform=window.Telegram?.WebApp?'telegram':'web';
state.lang=detectLanguage(getTelegramUser()?.language_code||navigator.language||'en');
renderTopbar();renderBottomNav();renderModal();renderBettingSheet();
