import {betOptions,chips} from '../../data/betting.js';
import {state} from '../state.js';
import {addBet,totalBet} from '../domains/betting/betting.js';
export function renderBettingSheet(){const root=document.querySelector('#modal-root');root.insertAdjacentHTML('beforeend',`<div id="bet-overlay" class="bet-overlay" aria-hidden="true"><div class="bet-sheet" role="dialog" aria-label="Baccarat Betting"><div class="sheet-grab"></div><div class="bet-head"><span class="bet-title">Baccarat Betting</span><span class="test-badge">TEST MODE</span></div><div id="bet-grid" class="bet-grid"></div><div class="chip-title">CHIP</div><div id="chip-row" class="chip-row"></div><div class="amount-row"><input id="bet-amount-input" class="amount-input" type="number" min="0" step="1" inputmode="numeric" placeholder="직접 금액 입력"><button class="max-btn" data-bet-max>MAX</button></div><div class="bet-summary"><span>선택 금액</span><strong><span id="selected-amount">0</span> P</strong></div><button id="bet-confirm" class="bet-confirm" data-bet-confirm disabled>베팅 확인</button><button class="bet-close" data-bet-close>닫기</button></div></div>`);renderBetOptions();renderChips()}
export function renderBetOptions(){const el=document.querySelector('#bet-grid');if(!el)return;el.innerHTML=betOptions.map(o=>`<button class="bet-option ${state.selectedBet===o.id?'selected ':''}${o.id==='panda8'?'full':''}" data-bet-id="${o.id}"><span class="bet-name">${o.name}</span><span class="bet-type">${o.type}</span><div class="bet-odds">${o.odds}</div><div class="bet-amount">${(state.betAmounts[o.id]||0)} P</div></button>`).join('')}
export function renderChips(){const el=document.querySelector('#chip-row');if(!el)return;el.innerHTML=chips.map(c=>`<button class="chip ${state.selectedChip===c?'selected':''}" data-chip="${c}">${c}</button>`).join('')}
export function updateBetUI(){document.querySelector('#selected-amount').textContent=totalBet().toLocaleString();document.querySelector('#bet-confirm').disabled=totalBet()<=0;renderBetOptions();renderChips()}
export function openBetting(){const overlay=document.querySelector('#bet-overlay');const room=document.querySelector('#page-live-room');if(!overlay||!room)return;if(overlay.parentElement!==room)room.appendChild(overlay);overlay.classList.add('show');overlay.setAttribute('aria-hidden','false')}
export function closeBetting(){const overlay=document.querySelector('#bet-overlay');if(!overlay)return;overlay.classList.remove('show');overlay.setAttribute('aria-hidden','true')}
export function handleBetClick(e){const bet=e.target.closest('[data-bet-id]');if(bet){state.selectedBet=bet.dataset.betId;const input=document.querySelector('#bet-amount-input');addBet(state.selectedBet,Number(input.value)||state.selectedChip);input.value='';updateBetUI();return}const chip=e.target.closest('[data-chip]');if(chip){state.selectedChip=Number(chip.dataset.chip);document.querySelector('#bet-amount-input').value='';updateBetUI()}}
