const TEMP_WALLET='TXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX';
const TEMP_QR='https://api.qrserver.com/v1/create-qr-code/?size=220x220&data='+encodeURIComponent(TEMP_WALLET);

export function renderModal(){
  document.querySelector('#modal-root').innerHTML=`<div id="popup" class="popup" hidden style="display:none"><div class="popup-box wallet-popup"><button class="popup-x" data-modal-close aria-label="닫기">×</button><div id="popup-title" class="popup-title"></div><div id="popup-text" class="popup-content"></div></div></div>`
}
export function openModal(title,text){const p=document.querySelector('#popup');if(!p)return;p.hidden=false;p.style.display='flex';document.querySelector('#popup-title').textContent=title;document.querySelector('#popup-text').innerHTML=text}
export function openDepositModal(){openModal('충전신청',`<div class="wallet-network">USDT · TRC20</div><div class="qr-title">결제 QR코드</div><div class="qr-wrap"><img class="payment-qr" src="${TEMP_QR}" alt="USDT TRC20 결제 QR코드"></div><a class="qr-download" href="${TEMP_QR}" download="usdt-trc20-payment-qr.png" target="_blank" rel="noopener">QR코드 다운로드</a><div class="wallet-label">지갑 주소</div><div class="wallet-address">${TEMP_WALLET}</div><button class="wallet-copy" data-copy-wallet>지갑 주소 복사</button><div class="warning-box"><strong>🔴 중요</strong><span>이체 후 자동으로 포인트가 충전됩니다.</span><span>USDT 충전만 가능합니다. TRX를 이체하지 마세요.</span></div><button class="wallet-close" data-modal-close>닫기</button>`)}
export function openWithdrawModal(){const balance=document.querySelector('#user-balance')?.textContent||'0';openModal('출금신청',`<div class="withdraw-balance"><span>출금가능잔액</span><strong>${balance} P</strong></div><label class="wallet-input-label" for="withdraw-amount">출금금액</label><input id="withdraw-amount" class="wallet-input" type="number" min="0" inputmode="decimal" placeholder="출금금액을 입력하세요"><label class="wallet-input-label" for="withdraw-password">출금 비밀번호</label><div class="password-wrap"><span>🔒</span><input id="withdraw-password" class="wallet-input password-input" type="password" placeholder="출금비밀번호 입력"></div><div class="payment-method-title">결제수단</div><div class="payment-methods">${Array.from({length:5},(_,i)=>`<button class="payment-slot" data-payment-slot="${i}">+ 결제수단 추가</button>`).join('')}</div><button class="withdraw-confirm" data-withdraw-confirm>출금확인</button><button class="wallet-close" data-modal-close>닫기</button>`)}
export function closeModal(){const p=document.querySelector('#popup');if(p){p.hidden=true;p.style.display='none'}}
